# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

PortalAppBundle:
    resource: "@PortalAppBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@PortalUserBundle/Resources/config/routing.yml"


PortalDemoBundle:
    resource: "@PortalDemoBundle/Resources/config/routing.yml"
    prefix:   /
