# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login


PortalAppBundle:
    resource: "@PortalAppBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@PortalUserBundle/Resources/config/routing.yml"
    



facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google
    
