<?php

namespace Portal\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Portal\AppBundle\Entity\Event;

/**
 * HighfiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighfiveRepository extends EntityRepository
{
}
