<?php

namespace Portal\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Portal\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Get all users
     *
     * @param $order
     * @return array
     */
    public function getAllUsers($order = 'ASC')
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT u
                           FROM Portal\UserBundle\Entity\User u
                           ORDER BY u.created ' . $order);

        return $query->getResult();
    }
}
