<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121120123914 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526CBA364942");
        $this->addSql("DROP TABLE entry");
        $this->addSql("DROP INDEX IDX_9474526CBA364942 ON comment");
        $this->addSql("ALTER TABLE comment CHANGE entry_id event_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526C71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)");
        $this->addSql("CREATE INDEX IDX_9474526C71F7E88B ON comment (event_id)");
        $this->addSql("ALTER TABLE event CHANGE description description VARCHAR(255) NOT NULL, CHANGE tags tags VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE highfive CHANGE comment comment VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE user ADD gravatar VARCHAR(120) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE entry (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, author VARCHAR(100) NOT NULL, entry LONGTEXT NOT NULL, image VARCHAR(20) NOT NULL, tags LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526C71F7E88B");
        $this->addSql("DROP INDEX IDX_9474526C71F7E88B ON comment");
        $this->addSql("ALTER TABLE comment CHANGE event_id entry_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526CBA364942 FOREIGN KEY (entry_id) REFERENCES entry (id)");
        $this->addSql("CREATE INDEX IDX_9474526CBA364942 ON comment (entry_id)");
        $this->addSql("ALTER TABLE event CHANGE description description LONGTEXT NOT NULL, CHANGE tags tags LONGTEXT NOT NULL");
        $this->addSql("ALTER TABLE highfive CHANGE comment comment LONGTEXT NOT NULL");
        $this->addSql("ALTER TABLE user DROP gravatar");
    }
}
