<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121125185104 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE highfive ADD user_id INT DEFAULT NULL, DROP user");
        $this->addSql("ALTER TABLE highfive ADD CONSTRAINT FK_D9477DE8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)");
        $this->addSql("CREATE INDEX IDX_D9477DE8A76ED395 ON highfive (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE highfive DROP FOREIGN KEY FK_D9477DE8A76ED395");
        $this->addSql("DROP INDEX IDX_D9477DE8A76ED395 ON highfive");
        $this->addSql("ALTER TABLE highfive ADD user VARCHAR(255) NOT NULL, DROP user_id");
    }
}
