parameters:

    # Contact email address
    portal_app.emails.contact_email: info@arturgajewski.com

    # Max latest events
    portal_app.comments.max_latest_events: 5

    # Max latest highfives
    portal_app.comments.max_latest_highfives: 5

    # Should the recaptha service be enabled for form submits
    # with users that are not logged in?
    portal_app.enable_recaptha: true