PortalAppBundle_homepage:
    pattern:  /
    defaults: { _controller: PortalAppBundle:Page:index }
    requirements:
        _method:  GET
        
PortalAppBundle_about:
    pattern:  /about
    defaults: { _controller: PortalAppBundle:Page:about }
    requirements:
        _method:  GET
        
PortalAppBundle_contact:
    pattern:  /contact
    defaults: { _controller: PortalAppBundle:Page:contact }
    requirements:
        _method:  GET|POST

PortalAppBundle_event_create:
    pattern:  /event/create
    defaults: { _controller: PortalAppBundle:Event:create }

PortalAppBundle_event_view:
    pattern:  /event/{eventId}/{slug}
    defaults: { _controller: PortalAppBundle:Event:view }
