PortalAppBundle_homepage:
    pattern:  /
    defaults: { _controller: PortalAppBundle:Page:index }
    requirements:
        _method:  GET
        
PortalAppBundle_about:
    pattern:  /about
    defaults: { _controller: PortalAppBundle:Page:about }
    requirements:
        _method:  GET
        
PortalAppBundle_contact:
    pattern:  /contact
    defaults: { _controller: PortalAppBundle:Page:contact }
    requirements:
        _method:  GET|POST

PortalAppBundle_event_new:
    pattern:  /event/new
    defaults: { _controller: PortalAppBundle:Event:new }

PortalAppBundle_event_create:
    pattern:  /event/create
    defaults: { _controller: PortalAppBundle:Event:create }

PortalAppBundle_event_view:
    pattern:  /event/{eventId}
    defaults: { _controller: PortalAppBundle:Event:view }

PortalAppBundle_event_modify:
    pattern:  /event/modify/{eventId}
    defaults: { _controller: PortalAppBundle:Event:modify }

PortalAppBundle_event_search:
    pattern:  /search/event
    defaults: { _controller: PortalAppBundle:Event:search }

PortalAppBundle_all_events:
    pattern:  /events
    defaults: { _controller: PortalAppBundle:Event:showAll }

PortalAppBundle_all_events_with_sorting:
    pattern:  /events/{orderByType}/{orderType}
    defaults: { _controller: PortalAppBundle:Event:showAll }

PortalAppBundle_highfives_received:
    pattern:  /received
    defaults: { _controller: PortalAppBundle:Page:highFivesReceived }

PortalAppBundle_cv:
    pattern:  /cv
    defaults: { _controller: PortalAppBundle:Cv:view }

PortalAppBundle_cv_user:
    pattern:  /cv/{username}
    defaults: { _controller: PortalAppBundle:Cv:user }
