services:
    portal_app.twig.extension:
        class: Portal\AppBundle\Twig\Extensions\PortalAppExtension
        tags:
            - { name: twig.extension }
           
    portal_user.registration.form.type:
        class: Portal\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, @translator]
        tags:
            - { name: form.type, alias: portal_user_registration }

    portal_app.service.event:
        class:     Portal\AppBundle\Service\EventService
        arguments: ["@doctrine.orm.entity_manager", "@portal_app.repository.event", "@security.context"]

    portal_app.repository.event:
        class:           Portal\AppBundle\Entity\Event
        arguments:       [Portal\AppBundle\Entity\Event]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
